POST http://localhost:4000/reports
content-type: application/json

{
  "make": "audi",
  "model": "r8",
  "year": 2023,
  "mileage": 1000,
  "lng": 55,
  "lat": 35,
  "price": 920000
}

### Approve an existing report
PATCH http://localhost:4000/reports/4
content-type: application/json

{
  "approved": true
}

### Get an estimate for a existing vechicle

GET http://localhost:4000/reports?make=audi&model=r8&year=2023&mileage=1000&lng=55&lat=32