### Create a new user
POST http://localhost:3000/auth/signup
content-type:application/json

{
    "email":"test5@some.com",
    "password": "test123"
}

### Sign In a user
POST http://localhost:3000/auth/signin
content-type:application/json

{
    "email":"test4@some.com",
    "password": "test123"
}


### Get a user
GET http://localhost:3000/auth/4


### Get all user
GET http://localhost:3000/auth?email=test4@some.com


### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "password": "bbbbbbb"
}

### Delete a user
DELETE http://localhost:3000/auth/2

### Set a color
GET http://localhost:3000/auth/colors/blue

### Get a color
GET  http://localhost:3000/auth/colors